// flow-typed signature: 0328ca30ed1bbd5b637f44d533eb77b7
// flow-typed version: <<STUB>>/nextein_v1.0.0-beta25/flow_v0.57.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nextein'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nextein' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nextein/config' {
  declare module.exports: any;
}

declare module 'nextein/dist/components/link' {
  declare module.exports: any;
}

declare module 'nextein/dist/components/post' {
  declare module.exports: any;
}

declare module 'nextein/dist/components/posts' {
  declare module.exports: any;
}

declare module 'nextein/dist/config' {
  declare module.exports: any;
}

declare module 'nextein/dist/entries/env' {
  declare module.exports: any;
}

declare module 'nextein/dist/entries/load' {
  declare module.exports: any;
}

declare module 'nextein/dist/entries/process' {
  declare module.exports: any;
}

declare module 'nextein/dist/server' {
  declare module.exports: any;
}

declare module 'nextein/link' {
  declare module.exports: any;
}

declare module 'nextein/post' {
  declare module.exports: any;
}

declare module 'nextein/posts' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nextein/config.js' {
  declare module.exports: $Exports<'nextein/config'>;
}
declare module 'nextein/dist/components/link.js' {
  declare module.exports: $Exports<'nextein/dist/components/link'>;
}
declare module 'nextein/dist/components/post.js' {
  declare module.exports: $Exports<'nextein/dist/components/post'>;
}
declare module 'nextein/dist/components/posts.js' {
  declare module.exports: $Exports<'nextein/dist/components/posts'>;
}
declare module 'nextein/dist/config.js' {
  declare module.exports: $Exports<'nextein/dist/config'>;
}
declare module 'nextein/dist/entries/env.js' {
  declare module.exports: $Exports<'nextein/dist/entries/env'>;
}
declare module 'nextein/dist/entries/load.js' {
  declare module.exports: $Exports<'nextein/dist/entries/load'>;
}
declare module 'nextein/dist/entries/process.js' {
  declare module.exports: $Exports<'nextein/dist/entries/process'>;
}
declare module 'nextein/dist/server.js' {
  declare module.exports: $Exports<'nextein/dist/server'>;
}
declare module 'nextein/index' {
  declare module.exports: $Exports<'nextein'>;
}
declare module 'nextein/index.js' {
  declare module.exports: $Exports<'nextein'>;
}
declare module 'nextein/link.js' {
  declare module.exports: $Exports<'nextein/link'>;
}
declare module 'nextein/post.js' {
  declare module.exports: $Exports<'nextein/post'>;
}
declare module 'nextein/posts.js' {
  declare module.exports: $Exports<'nextein/posts'>;
}
